services:
  gosu:
    image: kapdap/gosu:${GOSU_VERSION:-latest}
    build:
      context: .
      args:
        GOSU_VERSION: ${GOSU_VERSION}
        GOSU_ARCHITECTURES: ${GOSU_ARCHITECTURES}
    environment:
      DEBUG: 1
      GPG_SIGS: ${GPG_SIGS}
